# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

include(FindPackageHandleStandardArgs)

set(_NVSHMEM_ROOT "${NVSHMEM_ROOT}")
if (NOT _NVSHMEM_ROOT AND NOT "$ENV{NVSHMEM_ROOT}" STREQUAL "")
  set(_NVSHMEM_ROOT "$ENV{NVSHMEM_ROOT}")
elseif (NOT _NVSHMEM_ROOT AND NOT "$ENV{NVCOMPILER_SHMEM_HOME}" STREQUAL "")
  set(_NVSHMEM_ROOT "$ENV{NVCOMPILER_SHMEM_HOME}")
elseif (NOT _NVSHMEM_ROOT AND NOT "$ENV{NVCOMPILER_COMM_LIBS_HOME}" STREQUAL "")
  set(_NVSHMEM_ROOT "$ENV{NVCOMPILER_COMM_LIBS_HOME}")
endif()

if (_NVSHMEM_ROOT)
  find_path(NVSHMEM_INCLUDE_DIR
    NAMES nvshmem.h
    HINTS "${_NVSHMEM_ROOT}"
    PATH_SUFFIXES include nvshmem/include
    NO_DEFAULT_PATH
  )
  find_library(NVSHMEM_HOST_LIBRARY
    NAMES nvshmem_host
    HINTS "${_NVSHMEM_ROOT}"
    PATH_SUFFIXES lib lib64 nvshmem/lib nvshmem/lib64
    NO_DEFAULT_PATH
  )
  find_library(NVSHMEM_DEVICE_LIBRARY
    NAMES nvshmem_device
    HINTS "${_NVSHMEM_ROOT}"
    PATH_SUFFIXES lib lib64 nvshmem/lib nvshmem/lib64
    NO_DEFAULT_PATH
  )
else()
  find_path(NVSHMEM_INCLUDE_DIR NAMES nvshmem.h PATHS ENV CPATH)
  find_library(NVSHMEM_HOST_LIBRARY NAMES nvshmem_host PATHS ENV LIBRARY_PATH ENV LD_LIBRARY_PATH)
  find_library(NVSHMEM_DEVICE_LIBRARY NAMES nvshmem_device PATHS ENV LIBRARY_PATH ENV LD_LIBRARY_PATH)
endif()

find_package_handle_standard_args(NVSHMEM
  REQUIRED_VARS NVSHMEM_HOST_LIBRARY NVSHMEM_DEVICE_LIBRARY NVSHMEM_INCLUDE_DIR
)

if (NVSHMEM_FOUND AND NOT TARGET NVSHMEM::host)
  add_library(NVSHMEM::host UNKNOWN IMPORTED)
  set_target_properties(NVSHMEM::host PROPERTIES
    IMPORTED_LOCATION "${NVSHMEM_HOST_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${NVSHMEM_INCLUDE_DIR}"
  )
endif()

if (NVSHMEM_FOUND AND NOT TARGET NVSHMEM::device)
  add_library(NVSHMEM::device UNKNOWN IMPORTED)
  set_target_properties(NVSHMEM::device PROPERTIES
    IMPORTED_LOCATION "${NVSHMEM_DEVICE_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${NVSHMEM_INCLUDE_DIR}"
  )
endif()

mark_as_advanced(NVSHMEM_INCLUDE_DIR NVSHMEM_HOST_LIBRARY NVSHMEM_DEVICE_LIBRARY)
unset(_NVSHMEM_ROOT)
