# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

include(FindPackageHandleStandardArgs)

set(_NCCL_ROOT "${NCCL_ROOT}")
if (NOT _NCCL_ROOT AND NOT "$ENV{NCCL_ROOT}" STREQUAL "")
  set(_NCCL_ROOT "$ENV{NCCL_ROOT}")
elseif (NOT _NCCL_ROOT AND NOT "$ENV{NVCOMPILER_NCCL_HOME}" STREQUAL "")
  set(_NCCL_ROOT "$ENV{NVCOMPILER_NCCL_HOME}")
elseif (NOT _NCCL_ROOT AND NOT "$ENV{NVCOMPILER_COMM_LIBS_HOME}" STREQUAL "")
  set(_NCCL_ROOT "$ENV{NVCOMPILER_COMM_LIBS_HOME}")
endif()

if (_NCCL_ROOT)
  find_path(NCCL_INCLUDE_DIR
    NAMES nccl.h
    HINTS "${_NCCL_ROOT}"
    PATH_SUFFIXES include nccl/include
    NO_DEFAULT_PATH
  )
  find_library(NCCL_LIBRARY
    NAMES nccl
    HINTS "${_NCCL_ROOT}"
    PATH_SUFFIXES lib lib64 nccl/lib nccl/lib64
    NO_DEFAULT_PATH
  )
else()
  set(_NCCL_NVHPC_ROOT
      "${CUDECOMP_NVHPC_SDK_ROOT}/comm_libs/${CUDAToolkit_VERSION_MAJOR}.${CUDAToolkit_VERSION_MINOR}/nccl")
  if (CUDECOMP_NVHPC_SDK_ROOT AND IS_DIRECTORY "${_NCCL_NVHPC_ROOT}")
    list(APPEND _NCCL_PATHS "${_NCCL_NVHPC_ROOT}")
  endif()
  find_path(NCCL_INCLUDE_DIR
    NAMES nccl.h
    PATHS ${_NCCL_PATHS} ENV CPATH
    PATH_SUFFIXES include
  )
  find_library(NCCL_LIBRARY
    NAMES nccl
    PATHS ${_NCCL_PATHS} ENV LIBRARY_PATH ENV LD_LIBRARY_PATH
    PATH_SUFFIXES lib lib64
  )
endif()

if (NCCL_INCLUDE_DIR)
  file(STRINGS "${NCCL_INCLUDE_DIR}/nccl.h" _NCCL_VERSION_LINES
       REGEX "^#define NCCL_(MAJOR|MINOR|PATCH) +[0-9]+$")
  foreach(_NCCL_COMPONENT MAJOR MINOR PATCH)
    string(REGEX MATCH "#define NCCL_${_NCCL_COMPONENT} +([0-9]+)" _NCCL_VERSION_LINE
                 "${_NCCL_VERSION_LINES}")
    set(NCCL_VERSION_${_NCCL_COMPONENT} "${CMAKE_MATCH_1}")
  endforeach()
  if (DEFINED NCCL_VERSION_MAJOR AND DEFINED NCCL_VERSION_MINOR AND DEFINED NCCL_VERSION_PATCH)
    set(NCCL_VERSION "${NCCL_VERSION_MAJOR}.${NCCL_VERSION_MINOR}.${NCCL_VERSION_PATCH}")
  endif()
endif()

find_package_handle_standard_args(NCCL
  REQUIRED_VARS NCCL_LIBRARY NCCL_INCLUDE_DIR
  VERSION_VAR NCCL_VERSION
)

if (NCCL_FOUND AND NOT TARGET NCCL::NCCL)
  add_library(NCCL::NCCL UNKNOWN IMPORTED)
  set_target_properties(NCCL::NCCL PROPERTIES
    IMPORTED_LOCATION "${NCCL_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${NCCL_INCLUDE_DIR}"
  )
endif()

mark_as_advanced(NCCL_INCLUDE_DIR NCCL_LIBRARY)
unset(_NCCL_ROOT)
unset(_NCCL_NVHPC_ROOT)
unset(_NCCL_PATHS)
unset(_NCCL_VERSION_LINES)
unset(_NCCL_VERSION_LINE)
unset(_NCCL_COMPONENT)
