# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

include(FindPackageHandleStandardArgs)

set(_CUTENSOR_ROOT "${CUTENSOR_ROOT}")
if (NOT _CUTENSOR_ROOT AND NOT "$ENV{CUTENSOR_ROOT}" STREQUAL "")
  set(_CUTENSOR_ROOT "$ENV{CUTENSOR_ROOT}")
elseif (NOT _CUTENSOR_ROOT AND NOT "$ENV{NVCOMPILER_MATH_LIBS_HOME}" STREQUAL "")
  set(_CUTENSOR_ROOT "$ENV{NVCOMPILER_MATH_LIBS_HOME}")
endif()

set(_CUTENSOR_TARGET_NAMES "${CMAKE_SYSTEM_PROCESSOR}-linux")
if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
  list(APPEND _CUTENSOR_TARGET_NAMES sbsa-linux)
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|x86_64)$")
  list(APPEND _CUTENSOR_TARGET_NAMES x86_64-linux)
endif()

set(_CUTENSOR_INCLUDE_SUFFIXES include)
set(_CUTENSOR_LIBRARY_SUFFIXES lib lib64)
foreach(_CUTENSOR_TARGET_NAME IN LISTS _CUTENSOR_TARGET_NAMES)
  list(APPEND _CUTENSOR_INCLUDE_SUFFIXES "targets/${_CUTENSOR_TARGET_NAME}/include")
  list(APPEND _CUTENSOR_LIBRARY_SUFFIXES "targets/${_CUTENSOR_TARGET_NAME}/lib")
endforeach()
list(APPEND _CUTENSOR_LIBRARY_SUFFIXES
  "lib/${CUDAToolkit_VERSION_MAJOR}"
  "lib/${CUDAToolkit_VERSION_MAJOR}.${CUDAToolkit_VERSION_MINOR}"
)

if (_CUTENSOR_ROOT)
  find_path(CUTENSOR_INCLUDE_DIR
    NAMES cutensor.h
    HINTS "${_CUTENSOR_ROOT}"
    PATH_SUFFIXES ${_CUTENSOR_INCLUDE_SUFFIXES}
    NO_DEFAULT_PATH
  )
  find_library(CUTENSOR_LIBRARY
    NAMES cutensor
    HINTS "${_CUTENSOR_ROOT}"
    PATH_SUFFIXES ${_CUTENSOR_LIBRARY_SUFFIXES}
    NO_DEFAULT_PATH
  )
else()
  set(_CUTENSOR_NVHPC_ROOT
      "${CUDECOMP_NVHPC_SDK_ROOT}/math_libs/${CUDAToolkit_VERSION_MAJOR}.${CUDAToolkit_VERSION_MINOR}")
  if (CUDECOMP_NVHPC_SDK_ROOT AND IS_DIRECTORY "${_CUTENSOR_NVHPC_ROOT}")
    list(APPEND _CUTENSOR_PATHS "${_CUTENSOR_NVHPC_ROOT}")
  endif()
  find_path(CUTENSOR_INCLUDE_DIR
    NAMES cutensor.h
    PATHS ${_CUTENSOR_PATHS} ENV CPATH
    PATH_SUFFIXES ${_CUTENSOR_INCLUDE_SUFFIXES}
  )
  find_library(CUTENSOR_LIBRARY
    NAMES cutensor
    PATHS ${_CUTENSOR_PATHS} ENV LIBRARY_PATH ENV LD_LIBRARY_PATH
    PATH_SUFFIXES ${_CUTENSOR_LIBRARY_SUFFIXES}
  )
endif()

if (CUTENSOR_INCLUDE_DIR)
  file(STRINGS "${CUTENSOR_INCLUDE_DIR}/cutensor.h" _CUTENSOR_VERSION_LINES
       REGEX "^#define CUTENSOR_(MAJOR|MINOR|PATCH) +[0-9]+")
  foreach(_CUTENSOR_COMPONENT MAJOR MINOR PATCH)
    string(REGEX MATCH "#define CUTENSOR_${_CUTENSOR_COMPONENT} +([0-9]+)" _CUTENSOR_VERSION_LINE
                 "${_CUTENSOR_VERSION_LINES}")
    set(CUTENSOR_VERSION_${_CUTENSOR_COMPONENT} "${CMAKE_MATCH_1}")
  endforeach()
  if (DEFINED CUTENSOR_VERSION_MAJOR AND DEFINED CUTENSOR_VERSION_MINOR AND DEFINED CUTENSOR_VERSION_PATCH)
    set(CUTENSOR_VERSION "${CUTENSOR_VERSION_MAJOR}.${CUTENSOR_VERSION_MINOR}.${CUTENSOR_VERSION_PATCH}")
  endif()
endif()

find_package_handle_standard_args(CUTENSOR
  REQUIRED_VARS CUTENSOR_LIBRARY CUTENSOR_INCLUDE_DIR
  VERSION_VAR CUTENSOR_VERSION
)

if (CUTENSOR_FOUND AND NOT TARGET CUTENSOR::CUTENSOR)
  add_library(CUTENSOR::CUTENSOR UNKNOWN IMPORTED)
  set_target_properties(CUTENSOR::CUTENSOR PROPERTIES
    IMPORTED_LOCATION "${CUTENSOR_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${CUTENSOR_INCLUDE_DIR}"
  )
endif()

mark_as_advanced(CUTENSOR_INCLUDE_DIR CUTENSOR_LIBRARY)
unset(_CUTENSOR_ROOT)
unset(_CUTENSOR_TARGET_NAMES)
unset(_CUTENSOR_TARGET_NAME)
unset(_CUTENSOR_INCLUDE_SUFFIXES)
unset(_CUTENSOR_LIBRARY_SUFFIXES)
unset(_CUTENSOR_NVHPC_ROOT)
unset(_CUTENSOR_PATHS)
unset(_CUTENSOR_VERSION_LINES)
unset(_CUTENSOR_VERSION_LINE)
unset(_CUTENSOR_COMPONENT)
