name: "Build"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  rocm-version: "7.2.0"
  openmpi-version: "5.0.10"

jobs:
  test-build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache ROCm installation
        id: cache-rocm
        uses: actions/cache@v5
        with:
          path: |
            /opt/rocm-${{ env.rocm-version }}/
          key: ${{ runner.os }}-${{ env.rocm-version }}

      - name: Cache OpenMPI installation
        id: cache-openmpi
        uses: actions/cache@v5
        with:
          path: |
            /opt/openmpi/
          key: ${{ runner.os }}-${{ env.openmpi-version }}-${{ env.rocm-version }}

      # Always sets path, cache restore does not do this for ROCm
      - name: Setup PATH
        run: |
          echo /opt/openmpi/bin >> $GITHUB_PATH
          echo /opt/rocm-${{ env.rocm-version }}/bin >> $GITHUB_PATH

      - name: Install ROCm
        if: steps.cache-rocm.outputs.cache-hit != 'true'
        uses: loostrum/rocm-installer@v0.2
        with:
          version: ${{ env.rocm-version }}
          packages: rocm-hip-runtime-dev hipcub-dev hipfft-dev hipfort-dev hiptensor-dev rccl-dev

      - name: Install OpenMPI
        if: steps.cache-openmpi.outputs.cache-hit != 'true'
        run: |
          wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${{ env.openmpi-version }}.tar.gz
          tar xzf openmpi-${{ env.openmpi-version }}.tar.gz
          cd openmpi-${{ env.openmpi-version}}
          CC=amdclang CXX=amdclang++ FC=amdflang ./configure --prefix=/opt/openmpi/ --with-rocm
          make -j
          sudo make install

      - name: Build hipDecomp
        run: |
          cmake -S . -B build -DHIPDECOMP_BUILD_EXTRAS=1 -DHIPDECOMP_BUILD_FORTRAN=1 -DCMAKE_HIP_ARCHITECTURES=gfx90a
          make -C build -j
