name: "Documentation"

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    name: "Build Documentation"
    
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: "Install dependencies"
      run: |
        sudo apt-get update && sudo apt-get install -y doxygen
        pip install -r docs/requirements.txt

    - name: "Build documentation"
      run: |
        cd docs
        export CUDECOMP_GIT_SHA=`git rev-parse HEAD`
        make html

    - name: "Upload documentation"
      uses: actions/upload-artifact@v4
      with:
        name: cudecomp_docs
        path: docs/_build/html


  deploy-documentation:
    runs-on: ubuntu-latest
    needs: build-documentation
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - name: "Deploy documentation"
      id: deployment
      uses: actions/deploy-pages@v4
